### ISSUE TITLE
Type folder (VITE App) is not generating for frappe & ERP Next Doctype

### ISSUE THREAD

**Issue by VIKRAM5555** [The-Commit-Company/frappe-types#9]
When I try to generate type for an existing doctype in frappe or ERPNext, there is no error being thrown, but type file is not being generated. Is it possible to generate types for frappe/erpnext doctypes?

**Comment by nikkothari22** [comment]
Hey @VIKRAM5555 

Are you generating types using the command line tool? 

Frappe and ERPNext Doctype types can only be generated via the command line tool.

**Comment by VIKRAM5555** [comment]
yes,we are using command line tool ( bench generate-types-for-doctype),but types not being generated for frappe/erpnext doctype

**Comment by nikkothari22** [comment]
Can you send me a screenshot of the CLI commands as well as the Type Generation Settings?

**Comment by VIKRAM5555** [comment]
https://drive.google.com/file/d/1rUOgG2Sn-4K86sP_0lIlsvvY8xh3MP_R/view?usp=sharing
https://drive.google.com/file/d/12vMzW08bUXUNdKBYMyUqgRRldq_ZIX5y/view?usp=sharing
https://drive.google.com/file/d/1Ndf_jawHVbDXATrnW-GGDWoKW0QiWF6k/view?usp=sharing
